name: swapnil_s_application4
description: A new Flutter project.
version: 1.0.3+22
environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  animated_toggle_switch: ^0.6.2
  cached_network_image: ^3.2.1
  change_app_package_name: ^1.1.0
  dartz: ^0.10.1
  dio: ^4.0.6
  firebase_core: ^2.13.1
  screenshot:
  flutter:
     sdk: flutter
  flutter_nfc_kit: ^3.3.3
  flutter_riverpod: ^2.1.3
  flutter_local_notifications:
  flutter_svg: ^1.1.6
  flutter_svg_provider: ^1.0.3
  grouped_list: ^5.1.2
  image_cropper: ^3.0.3
  image_picker: 0.8.6+4
  firebase_messaging:
  injectable: null
  intl: ^0.17.0
  nfc_manager: ^3.2.0
  page_transition: ^2.0.9
  permission_handler: ^10.2.0
  pinput: ^2.2.31
  pretty_dio_logger: ^1.2.0-beta-1
  qr_code_scanner: ^1.0.1
  share_plus: ^7.0.2
  shared_preferences: ^2.0.15
  uni_links: ^0.5.1
  url_launcher: ^6.1.11
  firebase_auth:
  video_player: ^2.6.1
  webview_flutter: ^4.2.1
  google_sign_in:
  google_fonts:
  card_swiper: ^2.0.4
  flutter_card_swiper: ^5.1.0
  flutter_keyboard_visibility: ^5.4.1
  drag_and_drop_lists: ^0.3.3
  scan: ^1.6.0
  flutter_facebook_auth: ^5.0.8
  json_annotation: ^4.8.1
  file_picker: ^5.3.3
  syncfusion_flutter_pdfviewer: ^20.4.54
  string_to_hex: ^0.2.2
  image_gallery_saver: ^2.0.3
  flutter_colorpicker: ^1.0.3
  path_provider: ^2.1.1
  app_links: ^3.4.5
  go_router: ^12.1.3
  sign_in_with_apple: ^5.0.0
  http:

dev_dependencies:
  build_runner: null
  flutter_test:
    sdk: flutter
  freezed: null
  json_serializable: ^6.7.1
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/shades/
    - assets/newIcons/
    - assets/final-screens/images/
    - assets/how/

    - assets/profile_images/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Black.ttf
          weight: 600
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto-BlackItalic.ttf
          weight: 600
        - asset: assets/fonts/Roboto-Mediumitalic.ttf
          weight: 500
